from fastapi import FastAPI, BackgroundTasks, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from database import get_db
import json
import asyncio
from typing import List
import datetime

app = FastAPI(title="ReDi 2.0 Backend", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ConnectionManager:
    def __init__(self):
        self.active_connections: List[WebSocket] = []
        self.integrity_score = 100

    async def connect(self, websocket: WebSocket):
        await websocket.accept()
        self.active_connections.append(websocket)
        await websocket.send_json({"type": "score_update", "score": self.integrity_score})

    def disconnect(self, websocket: WebSocket):
        self.active_connections.remove(websocket)

    async def broadcast(self, message: dict):
        for connection in self.active_connections:
            try:
                await connection.send_json(message)
            except:
                pass

manager = ConnectionManager()
db = get_db()

@app.on_event("startup")
async def startup_event():
    print("ReDi 2.0 Backend Started Successfully.")
    print("Supabase connected.")

@app.get("/")
def read_root():
    return {"status": "ok"}

@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    await manager.connect(websocket)
    try:
        while True:
            data = await websocket.receive_text()
    except WebSocketDisconnect:
        manager.disconnect(websocket)

@app.post("/simulate_drift")
async def simulate_drift(background_tasks: BackgroundTasks):
    background_tasks.add_task(run_real_audit)
    return {"status": "Audit started"}

async def notify_drift(mock_detection):
    manager.integrity_score = max(0, manager.integrity_score - mock_detection['severity'])
    await manager.broadcast({"type": "score_update", "score": manager.integrity_score})
    await manager.broadcast({"type": "new_detection", "data": mock_detection})
    
    import random
    report_id = f"REP-{random.randint(100000, 999999)}"
    mock_report = f"""# RBI Compliance Incident Report
**Date:** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Rule Violated:** {mock_detection['rule_code']}
**Source Document:** {mock_detection['source_document']}

## 1. Description of Breach
{mock_detection['description']}

## 2. Evidence (Supabase Source)
**Criteria Failed:** {mock_detection['failed_value']}
**DB Record Context:** {mock_detection['evidence']}

## 3. Impact & Penalty
**Integrity Score Impact:** -{mock_detection['severity']}%
**Regulatory/Legal Penalty:** {mock_detection['company_penalty']}
**Immediate Action Required:** {mock_detection['action']}

*Auto-Generated by ReDi Action Agent.*
"""
    await asyncio.sleep(0.5)
    await manager.broadcast({
        "type": "new_report",
        "report_id": report_id,
        "content": mock_report
    })

async def run_real_audit():
    try:
        # Reset score and clear UI to prevent duplicates
        manager.integrity_score = 100
        await manager.broadcast({"type": "clear_detections"})
        await asyncio.sleep(0.5)

        # 1. Check Merchants
        merchants_resp = db.table('merchants').select("*").execute()
        merchants = merchants_resp.data
        
        # Track bank hashes for mule ring detection
        bank_hashes = {}

        for m in merchants:
            # Drift 1: KYC Overdue
            if m.get('kyc_status') == 'PENDING':
                ob_date_str = m.get('onboarding_date')
                if ob_date_str:
                    try:
                        ob_date = datetime.datetime.fromisoformat(ob_date_str.replace("Z", "+00:00")).replace(tzinfo=None)
                        # Specific to prompt: Today is March 28, 2026
                        now = datetime.datetime(2026, 3, 28)
                        if (now - ob_date).days > 5:
                            await notify_drift({
                                "type": "drift_detected",
                                "rule_code": "PA_KYC_001",
                                "source_document": "RBI/2023-24/MD-PA",
                                "description": "Merchant verification must be completed within 5 days. Account remained PENDING past timeline.",
                                "failed_value": f"Status PENDING for {(now-ob_date).days} days",
                                "severity": 10,
                                "action": "FREEZE_ACCOUNT",
                                "company_penalty": "Suspension of nodal account settlements",
                                "evidence": f"Merchant: {m.get('merchant_name')} | ID: {m.get('id')}"
                            })
                            await asyncio.sleep(0.5)
                    except: pass
            
            # Drift 2: Mule Ring
            b_hash = m.get('bank_account_hash')
            name = m.get('merchant_name')
            if b_hash:
                if b_hash in bank_hashes:
                    # Detected a collision
                    await notify_drift({
                        "type": "drift_detected",
                        "rule_code": "AML_030",
                        "source_document": "PMLA/RBI_SLA",
                        "description": "Coordinated money-mule network detected. Multiple distinct merchants trace to the exact same bank routing hash.",
                        "failed_value": f"Duplicate Hash: {b_hash}",
                        "severity": 20,
                        "action": "REPORT_TO_FIU",
                        "company_penalty": "Severe AML non-compliance fines up to ₹5 Cr & Criminal Investigation",
                        "evidence": f"{name} and {bank_hashes[b_hash]} share a bank account."
                    })
                    await asyncio.sleep(0.5)
                else:
                    bank_hashes[b_hash] = name

        # 2. Check Transactions
        txns_resp = db.table('transactions').select("*").execute()
        for t in txns_resp.data:
            try:
                tid = t.get('id')
                
                # Drift 3: UPI Latency
                latency = t.get('latency_ms')
                if latency and int(latency) > 10000:
                    await notify_drift({
                        "type": "drift_detected",
                        "rule_code": "TECH_005/SLA",
                        "source_document": "NPCI Framework 2024",
                        "description": "Transaction processing latency exceeds the 10-second NPCI mandate.",
                        "failed_value": f"Latency: {latency} ms",
                        "severity": 5,
                        "action": "FLAG_FOR_AUDIT",
                        "company_penalty": "Repeated SLA breaches yield ₹1 Lakh NPCI penalty per day",
                        "evidence": f"Txn ID: {tid}"
                    })
                    
                # Drift 4: Data Sovereignty
                loc = str(t.get('server_location', '')).strip().upper()
                if loc and loc not in ('IN-WEST', 'IN-SOUTH', 'NONE', ''):
                     await notify_drift({
                        "type": "drift_detected",
                        "rule_code": "TECH_001",
                        "source_document": "Data Sovereignty Law",
                        "description": "All payment data must be stored exclusively in India. Illegal overseas routing detected.",
                        "failed_value": f"Server Location: {loc}",
                        "severity": 25,
                        "action": "REVOKE_LICENSE",
                        "company_penalty": "Immediate License Revocation and Supreme Court injunctions",
                        "evidence": f"Txn ID: {tid} processed overseas"
                    })
                     
                # Drift 5: Transaction Limit
                amount = t.get('amount_inr')
                if amount and float(amount) > 2500000:
                     await notify_drift({
                        "type": "drift_detected",
                        "rule_code": "PA_LIMIT_001",
                        "source_document": "RBI/2023-24/MD-PA",
                        "description": "Cross-border transaction amount exceeds the strict ₹25,00,000 regulatory ceiling.",
                        "failed_value": f"Amount: ₹{amount}",
                        "severity": 15,
                        "action": "BLOCK_TRANSACTION",
                        "company_penalty": "Auditor scrutiny and ₹50 Lakh fine for enabling shadow capital flows",
                        "evidence": f"Txn ID: {tid} | Value: {amount}"
                    })
                     
                # Drift 6: Missing Purpose Code
                p_code = t.get('purpose_code')
                if p_code is None or str(p_code).strip() == "" or str(p_code).strip().upper() == "NULL":
                     await notify_drift({
                        "type": "drift_detected",
                        "rule_code": "FEMA_01",
                        "source_document": "FEMA Cross-Border Rules",
                        "description": "Cross-border transaction missing mandatory FEMA purpose code reporting.",
                        "failed_value": f"Purpose Code: MISSING",
                        "severity": 10,
                        "action": "HOLD_FUNDS",
                        "company_penalty": "FEMA violation triggering ED (Enforcement Directorate) inquiry",
                        "evidence": f"Txn ID: {tid} lacks code context."
                    })
                     
                # Drift 7: Predictive 2FA
                auth = t.get('auth_factors')
                date_str = str(t.get('txn_date', ''))
                if auth and int(auth) == 1 and ("2026-04" in date_str or "2026-05" in date_str):
                     await notify_drift({
                        "type": "drift_detected",
                        "rule_code": "TECH_031",
                        "source_document": "RBI Upcoming Mandates",
                        "description": "Scheduled predictive monitoring flagged a future transaction enforcing only 1 auth factor post April 1 deadline.",
                        "failed_value": f"Auth factors: {auth} (Expected: 2)",
                        "severity": 5,
                        "action": "PREVENTATIVE_BLOCK",
                        "company_penalty": "Warning: Pre-compliance failure.",
                        "evidence": f"Txn ID: {tid} | Scheduled: {date_str}"
                    })
            except Exception as loop_e:
                print(f"Skipped a transaction row due to parse error: {loop_e}")

        # 3. Check Escrow Ledger
        esc_resp = db.table('escrow_ledger').select("*").execute()
        for e in esc_resp.data:
            try:
                f_type = str(e.get('fund_type', '')).strip().upper()
                acc = str(e.get('account_label', '')).strip().upper()
                
                # Drift 8: Fund Segregation
                if f_type == 'IMPORT' and acc == 'ECA':
                     await notify_drift({
                        "type": "drift_detected",
                        "rule_code": "ESC_OPS_007",
                        "source_document": "RBI Escrow Guidelines",
                        "description": "Escrow mismatch: IMPORT type funds strictly must land in an ICA (Internal account) first.",
                        "failed_value": f"Fund Type '{f_type}' routed to '{acc}'",
                        "severity": 20,
                        "action": "REJECT_CREDIT",
                        "company_penalty": "Severe Commingling Fine of ₹3 Crores and RBI Escrow freeze",
                        "evidence": f"Ledger ID: {e.get('id')}"
                    })
            except Exception as loop_e:
                print(f"Skipped escrow row: {loop_e}")
                 
        # 4. Check Infrastructure
        infra_resp = db.table('infrastructure').select("*").execute()
        for i in infra_resp.data:
            try:
                # Drift 9: Net Worth Cliff
                nw = i.get('current_net_worth_inr')
                if nw and float(nw) < 250000000:
                     await notify_drift({
                        "type": "drift_detected",
                        "rule_code": "PA_NW_002",
                        "source_document": "RBI/2023-24/MD-PA",
                        "description": "Entity current net worth has fallen below the ₹25 Cr mandate required by March 31.",
                        "failed_value": f"Net Worth: ₹{float(nw)/10000000} Cr",
                        "severity": 25,
                        "action": "REVOKE_LICENSE",
                        "company_penalty": "Permanent revocation of PA-CB License.",
                        "evidence": f"Entity: {i.get('entity_name')}"
                    })
                     
                # Drift 10: SLA/RTO Breach
                rto = i.get('rto_hours')
                if rto and int(rto) > 2:
                     await notify_drift({
                        "type": "drift_detected",
                        "rule_code": "TECH_012",
                        "source_document": "RBI Infrastructure SLA",
                        "description": "Recovery Time Objective (RTO) limit breached. Systems take too long to recover from outages.",
                        "failed_value": f"RTO: {rto} hours (Max: 2 hours)",
                        "severity": 10,
                        "action": "ESCALATE_TO_BOARD",
                        "company_penalty": "IT Suspension by RBI until architecture fixes are proven.",
                        "evidence": f"Entity: {i.get('entity_name')} | Recorded RTO: {rto}h"
                    })
            except Exception as loop_e:
                 print(f"Skipped infra row: {loop_e}")

    except Exception as e:
        print(f"Audit Error: {e}")
